baseurl: ""
title: "Iota Tech"

plugins:
  - jekyll-postcss

include: ["node_modules/tailwindcss"]

sass:
  load_paths:
    - _sass
    - node_modules

exclude:
  - .gitignore
  - bin
  - package-lock.json
  - postcss.config.js
  - README.md
