baseurl: ""
title: "Iota Tech"

plugins:
  - jekyll-postcss

include: ["node_modules/tailwindcss"]

postcss:
  cache: false

exclude:
  - .gitignore
  - bin
  - package-lock.json
  - postcss.config.js
  - README.md
